language: java

dist: xenial

services:
   - xvbf
   - docker

jdk: openjdk8


install: true

cache:
   directories:
      - $HOME/.m2


script:
- mvn -f airport-management/pom.xml clean verify






